name: Build and Deploy Docker Container with Volume

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'
      - '**/*.sql'
      - '**/.env'
      - '**/my.cnf'
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày vào lúc 00:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: $GITHUB_SHA
        restore-keys: |
          $GITHUB_SHA

    - name: Build Docker image
      run: |
        docker-compose build

    - name: Push Docker image
      run: |
        docker-compose push

    - name: Stop and remove old container
      run: |
        docker-compose down

    - name: Deploy Docker container with volume
      run: |
        docker-compose up -d --build -v ${GITHUB_WORKSPACE}:/app

    - name: Verify container is running
      run: |
        docker-compose ps